name: Daily EchoPulse Radar

on:
  schedule:
    # سيتم التشغيل الساعة 04:40 صباحاً بتوقيت جرينتش (UTC)
    - cron: "15 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          # بما أن الملف في الجذر، ننادي عليه مباشرة
          pip install -r requirements.txt

      - name: Run EchoPulse Script
        run: |
          # تشغيل السكريبت من الجذر مباشرة
          python main.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Tech Radar: $(date +'%Y-%m-%d')" || exit 0
          git push
